"""add meal plans

Revision ID: 0fc2516c6936
Revises: b553d39b3d34
Create Date: 2026-07-17 13:18:40.099667

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fc2516c6936"
down_revision: str | Sequence[str] | None = "b553d39b3d34"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meal_plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("start_date", name="uq_meal_plans_start_date"),
    )
    op.create_index(
        op.f("ix_meal_plans_start_date"), "meal_plans", ["start_date"], unique=False
    )
    op.create_table(
        "meal_plan_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("meal_plan_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("planned_date", sa.Date(), nullable=False),
        sa.Column("meal_type", sa.String(length=50), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["meal_plan_id"], ["meal_plans.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "meal_plan_id", "planned_date", "meal_type", name="uq_meal_plan_entry_slot"
        ),
    )
    op.create_index(
        op.f("ix_meal_plan_entries_meal_plan_id"),
        "meal_plan_entries",
        ["meal_plan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meal_plan_entries_planned_date"),
        "meal_plan_entries",
        ["planned_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meal_plan_entries_recipe_id"),
        "meal_plan_entries",
        ["recipe_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_meal_plan_entries_recipe_id"), table_name="meal_plan_entries"
    )
    op.drop_index(
        op.f("ix_meal_plan_entries_planned_date"), table_name="meal_plan_entries"
    )
    op.drop_index(
        op.f("ix_meal_plan_entries_meal_plan_id"), table_name="meal_plan_entries"
    )
    op.drop_table("meal_plan_entries")
    op.drop_index(op.f("ix_meal_plans_start_date"), table_name="meal_plans")
    op.drop_table("meal_plans")
    # ### end Alembic commands ###
